server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/copyright_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: CD577903
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  mvc:
    static-path-pattern: /uploads/**

  web:
    resources:
      static-locations: file:uploads/